version: '3'

tasks:
  new:
    cmds:
      - mkdir {{ .day }}
      - touch {{ .day }}/main.go
      - touch {{ .day }}/data.txt
      - touch {{ .day }}/test.txt
      - echo "package main" >> {{ .day }}/main.go
      - echo "func main() {} " >> {{ .day }}/main.go
