[package]
name = "x2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "x2022"
path = "Day2/sln.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
